package Model;
// Generated 01-oct-2017 16:14:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Activitytype generated by hbm2java
 */
public class Activitytype  implements java.io.Serializable {


     private Long idActivityType;
     private String nameActivityType;
     private Set<Programming> programmings = new HashSet<Programming>(0);

    public Activitytype() {
    }

	
    public Activitytype(String nameActivityType) {
        this.nameActivityType = nameActivityType;
    }
    public Activitytype(String nameActivityType, Set<Programming> programmings) {
       this.nameActivityType = nameActivityType;
       this.programmings = programmings;
    }
   
    public Long getIdActivityType() {
        return this.idActivityType;
    }
    
    public void setIdActivityType(Long idActivityType) {
        this.idActivityType = idActivityType;
    }
    public String getNameActivityType() {
        return this.nameActivityType;
    }
    
    public void setNameActivityType(String nameActivityType) {
        this.nameActivityType = nameActivityType;
    }
    public Set<Programming> getProgrammings() {
        return this.programmings;
    }
    
    public void setProgrammings(Set<Programming> programmings) {
        this.programmings = programmings;
    }




}


