package Model;
// Generated 01-oct-2017 16:14:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Areasena generated by hbm2java
 */
public class Areasena  implements java.io.Serializable {


     private Long idAreaSena;
     private String nameArea;
     private Set<Groupp> groupps = new HashSet<Groupp>(0);

    public Areasena() {
    }

	
    public Areasena(String nameArea) {
        this.nameArea = nameArea;
    }
    public Areasena(String nameArea, Set<Groupp> groupps) {
       this.nameArea = nameArea;
       this.groupps = groupps;
    }
   
    public Long getIdAreaSena() {
        return this.idAreaSena;
    }
    
    public void setIdAreaSena(Long idAreaSena) {
        this.idAreaSena = idAreaSena;
    }
    public String getNameArea() {
        return this.nameArea;
    }
    
    public void setNameArea(String nameArea) {
        this.nameArea = nameArea;
    }
    public Set<Groupp> getGroupps() {
        return this.groupps;
    }
    
    public void setGroupps(Set<Groupp> groupps) {
        this.groupps = groupps;
    }




}


