package Model;
// Generated 01-oct-2017 16:14:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Institute generated by hbm2java
 */
public class Institute  implements java.io.Serializable {


     private Long idInstitute;
     private Locality locality;
     private Neigborhood neigborhood;
     private Phone phone;
     private Spaceformation spaceformation;
     private String nameInstitute;
     private String headquarters;
     private String address;
     private String email;
     private Set<Programming> programmings = new HashSet<Programming>(0);

    public Institute() {
    }

	
    public Institute(Locality locality, Neigborhood neigborhood, Phone phone, Spaceformation spaceformation, String nameInstitute, String headquarters, String address, String email) {
        this.locality = locality;
        this.neigborhood = neigborhood;
        this.phone = phone;
        this.spaceformation = spaceformation;
        this.nameInstitute = nameInstitute;
        this.headquarters = headquarters;
        this.address = address;
        this.email = email;
    }
    public Institute(Locality locality, Neigborhood neigborhood, Phone phone, Spaceformation spaceformation, String nameInstitute, String headquarters, String address, String email, Set<Programming> programmings) {
       this.locality = locality;
       this.neigborhood = neigborhood;
       this.phone = phone;
       this.spaceformation = spaceformation;
       this.nameInstitute = nameInstitute;
       this.headquarters = headquarters;
       this.address = address;
       this.email = email;
       this.programmings = programmings;
    }
   
    public Long getIdInstitute() {
        return this.idInstitute;
    }
    
    public void setIdInstitute(Long idInstitute) {
        this.idInstitute = idInstitute;
    }
    public Locality getLocality() {
        return this.locality;
    }
    
    public void setLocality(Locality locality) {
        this.locality = locality;
    }
    public Neigborhood getNeigborhood() {
        return this.neigborhood;
    }
    
    public void setNeigborhood(Neigborhood neigborhood) {
        this.neigborhood = neigborhood;
    }
    public Phone getPhone() {
        return this.phone;
    }
    
    public void setPhone(Phone phone) {
        this.phone = phone;
    }
    public Spaceformation getSpaceformation() {
        return this.spaceformation;
    }
    
    public void setSpaceformation(Spaceformation spaceformation) {
        this.spaceformation = spaceformation;
    }
    public String getNameInstitute() {
        return this.nameInstitute;
    }
    
    public void setNameInstitute(String nameInstitute) {
        this.nameInstitute = nameInstitute;
    }
    public String getHeadquarters() {
        return this.headquarters;
    }
    
    public void setHeadquarters(String headquarters) {
        this.headquarters = headquarters;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set<Programming> getProgrammings() {
        return this.programmings;
    }
    
    public void setProgrammings(Set<Programming> programmings) {
        this.programmings = programmings;
    }




}


