package Model;
// Generated 01-oct-2017 16:14:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Locality generated by hbm2java
 */
public class Locality  implements java.io.Serializable {


     private Long idLocality;
     private String nameLocality;
     private Set<Person> persons = new HashSet<Person>(0);
     private Set<Institute> institutes = new HashSet<Institute>(0);

    public Locality() {
    }

	
    public Locality(String nameLocality) {
        this.nameLocality = nameLocality;
    }
    public Locality(String nameLocality, Set<Person> persons, Set<Institute> institutes) {
       this.nameLocality = nameLocality;
       this.persons = persons;
       this.institutes = institutes;
    }
   
    public Long getIdLocality() {
        return this.idLocality;
    }
    
    public void setIdLocality(Long idLocality) {
        this.idLocality = idLocality;
    }
    public String getNameLocality() {
        return this.nameLocality;
    }
    
    public void setNameLocality(String nameLocality) {
        this.nameLocality = nameLocality;
    }
    public Set<Person> getPersons() {
        return this.persons;
    }
    
    public void setPersons(Set<Person> persons) {
        this.persons = persons;
    }
    public Set<Institute> getInstitutes() {
        return this.institutes;
    }
    
    public void setInstitutes(Set<Institute> institutes) {
        this.institutes = institutes;
    }




}


