package Model;
// Generated 01-oct-2017 16:14:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Neigborhood generated by hbm2java
 */
public class Neigborhood  implements java.io.Serializable {


     private Long idNeigBorhood;
     private String nameNeigBorhood;
     private Set<Institute> institutes = new HashSet<Institute>(0);

    public Neigborhood() {
    }

	
    public Neigborhood(String nameNeigBorhood) {
        this.nameNeigBorhood = nameNeigBorhood;
    }
    public Neigborhood(String nameNeigBorhood, Set<Institute> institutes) {
       this.nameNeigBorhood = nameNeigBorhood;
       this.institutes = institutes;
    }
   
    public Long getIdNeigBorhood() {
        return this.idNeigBorhood;
    }
    
    public void setIdNeigBorhood(Long idNeigBorhood) {
        this.idNeigBorhood = idNeigBorhood;
    }
    public String getNameNeigBorhood() {
        return this.nameNeigBorhood;
    }
    
    public void setNameNeigBorhood(String nameNeigBorhood) {
        this.nameNeigBorhood = nameNeigBorhood;
    }
    public Set<Institute> getInstitutes() {
        return this.institutes;
    }
    
    public void setInstitutes(Set<Institute> institutes) {
        this.institutes = institutes;
    }




}


