package Model;
// Generated 01-oct-2017 16:14:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Person generated by hbm2java
 */
public class Person  implements java.io.Serializable {


     private Long idPerson;
     private Locality locality;
     private Phone phone;
     private Userp userp;
     private String personNameVarchar;
     private long documentationNumber;
     private String address;
     private String neigborhood;
     private String email;
     private Set<Programming> programmings = new HashSet<Programming>(0);

    public Person() {
    }

	
    public Person(Locality locality, Phone phone, Userp userp, String personNameVarchar, long documentationNumber, String address, String neigborhood, String email) {
        this.locality = locality;
        this.phone = phone;
        this.userp = userp;
        this.personNameVarchar = personNameVarchar;
        this.documentationNumber = documentationNumber;
        this.address = address;
        this.neigborhood = neigborhood;
        this.email = email;
    }
    public Person(Locality locality, Phone phone, Userp userp, String personNameVarchar, long documentationNumber, String address, String neigborhood, String email, Set<Programming> programmings) {
       this.locality = locality;
       this.phone = phone;
       this.userp = userp;
       this.personNameVarchar = personNameVarchar;
       this.documentationNumber = documentationNumber;
       this.address = address;
       this.neigborhood = neigborhood;
       this.email = email;
       this.programmings = programmings;
    }
   
    public Long getIdPerson() {
        return this.idPerson;
    }
    
    public void setIdPerson(Long idPerson) {
        this.idPerson = idPerson;
    }
    public Locality getLocality() {
        return this.locality;
    }
    
    public void setLocality(Locality locality) {
        this.locality = locality;
    }
    public Phone getPhone() {
        return this.phone;
    }
    
    public void setPhone(Phone phone) {
        this.phone = phone;
    }
    public Userp getUserp() {
        return this.userp;
    }
    
    public void setUserp(Userp userp) {
        this.userp = userp;
    }
    public String getPersonNameVarchar() {
        return this.personNameVarchar;
    }
    
    public void setPersonNameVarchar(String personNameVarchar) {
        this.personNameVarchar = personNameVarchar;
    }
    public long getDocumentationNumber() {
        return this.documentationNumber;
    }
    
    public void setDocumentationNumber(long documentationNumber) {
        this.documentationNumber = documentationNumber;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getNeigborhood() {
        return this.neigborhood;
    }
    
    public void setNeigborhood(String neigborhood) {
        this.neigborhood = neigborhood;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set<Programming> getProgrammings() {
        return this.programmings;
    }
    
    public void setProgrammings(Set<Programming> programmings) {
        this.programmings = programmings;
    }




}


