package Model;
// Generated 01-oct-2017 16:14:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Phone generated by hbm2java
 */
public class Phone  implements java.io.Serializable {


     private Long idPhone;
     private long phonenumber;
     private Set<Person> persons = new HashSet<Person>(0);
     private Set<Institute> institutes = new HashSet<Institute>(0);

    public Phone() {
    }

	
    public Phone(long phonenumber) {
        this.phonenumber = phonenumber;
    }
    public Phone(long phonenumber, Set<Person> persons, Set<Institute> institutes) {
       this.phonenumber = phonenumber;
       this.persons = persons;
       this.institutes = institutes;
    }
   
    public Long getIdPhone() {
        return this.idPhone;
    }
    
    public void setIdPhone(Long idPhone) {
        this.idPhone = idPhone;
    }
    public long getPhonenumber() {
        return this.phonenumber;
    }
    
    public void setPhonenumber(long phonenumber) {
        this.phonenumber = phonenumber;
    }
    public Set<Person> getPersons() {
        return this.persons;
    }
    
    public void setPersons(Set<Person> persons) {
        this.persons = persons;
    }
    public Set<Institute> getInstitutes() {
        return this.institutes;
    }
    
    public void setInstitutes(Set<Institute> institutes) {
        this.institutes = institutes;
    }




}


