package Model;
// Generated 01-oct-2017 16:14:59 by Hibernate Tools 4.3.1



/**
 * Programming generated by hbm2java
 */
public class Programming  implements java.io.Serializable {


     private Long idProgramming;
     private Activitytype activitytype;
     private Groupp groupp;
     private Institute institute;
     private Person person;
     private Workingday workingday;
     private long hoursToWork;
     private String daysToWork;

    public Programming() {
    }

    public Programming(Activitytype activitytype, Groupp groupp, Institute institute, Person person, Workingday workingday, long hoursToWork, String daysToWork) {
       this.activitytype = activitytype;
       this.groupp = groupp;
       this.institute = institute;
       this.person = person;
       this.workingday = workingday;
       this.hoursToWork = hoursToWork;
       this.daysToWork = daysToWork;
    }
   
    public Long getIdProgramming() {
        return this.idProgramming;
    }
    
    public void setIdProgramming(Long idProgramming) {
        this.idProgramming = idProgramming;
    }
    public Activitytype getActivitytype() {
        return this.activitytype;
    }
    
    public void setActivitytype(Activitytype activitytype) {
        this.activitytype = activitytype;
    }
    public Groupp getGroupp() {
        return this.groupp;
    }
    
    public void setGroupp(Groupp groupp) {
        this.groupp = groupp;
    }
    public Institute getInstitute() {
        return this.institute;
    }
    
    public void setInstitute(Institute institute) {
        this.institute = institute;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    public Workingday getWorkingday() {
        return this.workingday;
    }
    
    public void setWorkingday(Workingday workingday) {
        this.workingday = workingday;
    }
    public long getHoursToWork() {
        return this.hoursToWork;
    }
    
    public void setHoursToWork(long hoursToWork) {
        this.hoursToWork = hoursToWork;
    }
    public String getDaysToWork() {
        return this.daysToWork;
    }
    
    public void setDaysToWork(String daysToWork) {
        this.daysToWork = daysToWork;
    }




}


