package Model;
// Generated 01-oct-2017 16:14:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Spaceformation generated by hbm2java
 */
public class Spaceformation  implements java.io.Serializable {


     private Long idSpaceFormation;
     private Typespaceformation typespaceformation;
     private String spaceFormation;
     private Set<Institute> institutes = new HashSet<Institute>(0);

    public Spaceformation() {
    }

	
    public Spaceformation(Typespaceformation typespaceformation, String spaceFormation) {
        this.typespaceformation = typespaceformation;
        this.spaceFormation = spaceFormation;
    }
    public Spaceformation(Typespaceformation typespaceformation, String spaceFormation, Set<Institute> institutes) {
       this.typespaceformation = typespaceformation;
       this.spaceFormation = spaceFormation;
       this.institutes = institutes;
    }
   
    public Long getIdSpaceFormation() {
        return this.idSpaceFormation;
    }
    
    public void setIdSpaceFormation(Long idSpaceFormation) {
        this.idSpaceFormation = idSpaceFormation;
    }
    public Typespaceformation getTypespaceformation() {
        return this.typespaceformation;
    }
    
    public void setTypespaceformation(Typespaceformation typespaceformation) {
        this.typespaceformation = typespaceformation;
    }
    public String getSpaceFormation() {
        return this.spaceFormation;
    }
    
    public void setSpaceFormation(String spaceFormation) {
        this.spaceFormation = spaceFormation;
    }
    public Set<Institute> getInstitutes() {
        return this.institutes;
    }
    
    public void setInstitutes(Set<Institute> institutes) {
        this.institutes = institutes;
    }




}


