package Model;
// Generated 01-oct-2017 16:14:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Typespaceformation generated by hbm2java
 */
public class Typespaceformation  implements java.io.Serializable {


     private Long idTypeSpaceFormation;
     private String nameSpaceFormation;
     private Set<Spaceformation> spaceformations = new HashSet<Spaceformation>(0);

    public Typespaceformation() {
    }

	
    public Typespaceformation(String nameSpaceFormation) {
        this.nameSpaceFormation = nameSpaceFormation;
    }
    public Typespaceformation(String nameSpaceFormation, Set<Spaceformation> spaceformations) {
       this.nameSpaceFormation = nameSpaceFormation;
       this.spaceformations = spaceformations;
    }
   
    public Long getIdTypeSpaceFormation() {
        return this.idTypeSpaceFormation;
    }
    
    public void setIdTypeSpaceFormation(Long idTypeSpaceFormation) {
        this.idTypeSpaceFormation = idTypeSpaceFormation;
    }
    public String getNameSpaceFormation() {
        return this.nameSpaceFormation;
    }
    
    public void setNameSpaceFormation(String nameSpaceFormation) {
        this.nameSpaceFormation = nameSpaceFormation;
    }
    public Set<Spaceformation> getSpaceformations() {
        return this.spaceformations;
    }
    
    public void setSpaceformations(Set<Spaceformation> spaceformations) {
        this.spaceformations = spaceformations;
    }




}


