package Model;
// Generated 01-oct-2017 16:14:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Typegroup generated by hbm2java
 */
public class Typegroup  implements java.io.Serializable {


     private Long idTypeGroup;
     private String nameTypeGroup;
     private Set<Groupp> groupps = new HashSet<Groupp>(0);

    public Typegroup() {
    }

	
    public Typegroup(String nameTypeGroup) {
        this.nameTypeGroup = nameTypeGroup;
    }
    public Typegroup(String nameTypeGroup, Set<Groupp> groupps) {
       this.nameTypeGroup = nameTypeGroup;
       this.groupps = groupps;
    }
   
    public Long getIdTypeGroup() {
        return this.idTypeGroup;
    }
    
    public void setIdTypeGroup(Long idTypeGroup) {
        this.idTypeGroup = idTypeGroup;
    }
    public String getNameTypeGroup() {
        return this.nameTypeGroup;
    }
    
    public void setNameTypeGroup(String nameTypeGroup) {
        this.nameTypeGroup = nameTypeGroup;
    }
    public Set<Groupp> getGroupps() {
        return this.groupps;
    }
    
    public void setGroupps(Set<Groupp> groupps) {
        this.groupps = groupps;
    }




}


