package Model;
// Generated 01-oct-2017 16:14:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Userp generated by hbm2java
 */
public class Userp  implements java.io.Serializable {


     private long idUser;
     private Rol rol;
     private String passwordU;
     private Set<Person> persons = new HashSet<Person>(0);

    public Userp() {
    }

	
    public Userp(long idUser, Rol rol, String passwordU) {
        this.idUser = idUser;
        this.rol = rol;
        this.passwordU = passwordU;
    }
    public Userp(long idUser, Rol rol, String passwordU, Set<Person> persons) {
       this.idUser = idUser;
       this.rol = rol;
       this.passwordU = passwordU;
       this.persons = persons;
    }
   
    public long getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(long idUser) {
        this.idUser = idUser;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public String getPasswordU() {
        return this.passwordU;
    }
    
    public void setPasswordU(String passwordU) {
        this.passwordU = passwordU;
    }
    public Set<Person> getPersons() {
        return this.persons;
    }
    
    public void setPersons(Set<Person> persons) {
        this.persons = persons;
    }




}


