package Model;
// Generated 01-oct-2017 16:14:59 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Workingday generated by hbm2java
 */
public class Workingday  implements java.io.Serializable {


     private Long idWorkingDay;
     private String workingDayName;
     private Date startTime;
     private Date finishTime;
     private Set<Programming> programmings = new HashSet<Programming>(0);

    public Workingday() {
    }

	
    public Workingday(String workingDayName, Date startTime, Date finishTime) {
        this.workingDayName = workingDayName;
        this.startTime = startTime;
        this.finishTime = finishTime;
    }
    public Workingday(String workingDayName, Date startTime, Date finishTime, Set<Programming> programmings) {
       this.workingDayName = workingDayName;
       this.startTime = startTime;
       this.finishTime = finishTime;
       this.programmings = programmings;
    }
   
    public Long getIdWorkingDay() {
        return this.idWorkingDay;
    }
    
    public void setIdWorkingDay(Long idWorkingDay) {
        this.idWorkingDay = idWorkingDay;
    }
    public String getWorkingDayName() {
        return this.workingDayName;
    }
    
    public void setWorkingDayName(String workingDayName) {
        this.workingDayName = workingDayName;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public Date getFinishTime() {
        return this.finishTime;
    }
    
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }
    public Set<Programming> getProgrammings() {
        return this.programmings;
    }
    
    public void setProgrammings(Set<Programming> programmings) {
        this.programmings = programmings;
    }




}


